---
title: "Homework 3"
author: "Put your name and student ID here"
date: '`r format(Sys.Date())`'
CJKmainfont: SimSun
output:
  pdf_document: 
    includes:
      header-includes:
        - \usepackage{xeCJK}
        - \usepackage{amsmath}
        - \usepackage{listings}
        - \usepackage{amsfonts}
        - \usepackage{amssymb}
    keep_tex: yes
    latex_engine: xelatex
---




**Q1**: Let $X_1,\dots,X_{15}$ be a simple random sample of $N(0,2^2)$. What is the distribution of
$$Y=\frac{X_1^2+\dots+X_{10}^2}{2(X_{11}^2+\dots+X_{15}^2)}?$$


**Q2**: Let $\boldsymbol Z = \boldsymbol c + \boldsymbol{AY}$, where $\boldsymbol Y$ is a random vector, $\boldsymbol A$ is a fixed matrix, and $\boldsymbol c$ is a fixed vector. Prove that

1. the expected value of $\boldsymbol Z$: $\mathbb E[\boldsymbol Z]=\boldsymbol c + \boldsymbol{A}\mathbb E[\boldsymbol Y],$

2. the covariance matrix of $\boldsymbol Z$: $\mathrm{Var}[\boldsymbol Z]=\boldsymbol A \mathrm{Var}[\boldsymbol Y] \boldsymbol A^\top$.


**Q3**: Let $X_1,\dots,X_n$ be iid sample from $N(\mu,\sigma^2)$, where $\mu,\sigma$ are unknown parameters. Which of the following are statistics? (  ) 多选题

A. $X_1+X_n-2\mu$

B. $(X_1-\mu)/\sigma$

C. $(\bar X-10)/5$

D. $\frac 1 n\sum_{i=1}^n(X_i-S_n)^2$


**Q4**: Suppose that $n=15,\bar x_{n}=168, s_n=11.43, x_{n+1}=170$. Find the values for $\bar x_{n+1},s_{n+1}^2$ and $s_{n+1}^{*2}$.


**Q5**: Show that if $X$ and $Y$ are independent exponential random variables with $\lambda = 1$,
then $X/Y$ follows an F distribution. Also, identify the degrees of freedom.

**Q6**: Suppose that $X=(X_1,\dots,X_n)^\top\sim N(\mathbf 0,I_n)$. Show that for any orthogonal matrix $U$, then $UX\sim N(\mathbf 0,I_n)$.

