---
title: "Homework 4"
author: "Put your name and student ID here"
date: '`r format(Sys.Date())`'
CJKmainfont: SimSun
output:
  pdf_document: 
    includes:
      header-includes:
        - \usepackage{xeCJK}
        - \usepackage{amsmath}
        - \usepackage{listings}
        - \usepackage{amsfonts}
        - \usepackage{amssymb}
    keep_tex: yes
    latex_engine: xelatex
---



**Q1**: Let $X_1,\dots,X_n$ be an iid sample of $N(1,2^2)$. Which of the following items are true? (   )

A. $\frac{\bar X-1}{2/\sqrt{n}}\sim t(n)$

B. $\frac{1}{4}\sum_{i=1}^n(X_i-1)^2\sim F(n,1)$

C. $\frac{\bar X-1}{\sqrt{2}/\sqrt{n}}\sim N(0,1)$

D. $\frac{1}{4}\sum_{i=1}^n(X_i-1)^2\sim \chi^2(n)$

**Q2**: Let $X_1,\dots,X_n$ be a simple random sample of normal population $N(\mu,\sigma^2)$. 

1. Find the mean and variance of $S_n^2$.

2. Show that $S_n^2\sim Gamma((n-1)/2,n/(2\sigma^2))$.


**Q3**: Let $X_1,\dots,X_n$ be a simple random sample of a distribution with mean $\mu$ and variance $\sigma^2$. Find the mean of $S_n^2$ and $S_n^{*2}$, respectively.

**Q4**: An iid sample $X_1,\dots,X_6$ is taken from the density $f_X(x)=3x^2,\ 0<x<1$. Find $P(X_{(6)}>0.75)$.

**Q5**: Let $X_1,\dots,X_m$ be a simple random sample of $N(\mu_1,\sigma_1^2)$, and $Y_1,\dots,Y_n$ ($n>3$) be a simple random sample of $N(\mu_2,\sigma_2^2)$, and the two samples are independent. Denote $S_X^{*2}$ and $S_Y^{*2}$ by the modified sample variances of $X_i$s and $Y_i$s, respectively. 

1. Show the PDF of the ratio of the two modified sample variances $S_X^{*2}/S_Y^{*2}$. 

2. Find the mean of $S_X^{*2}/S_Y^{*2}$, and compare it with the ratio of two population variances $\sigma_1^2/\sigma_2^2$.

(Hint: the mean of $F(m,n)$ distribution is $n/(n-2)$ when $n>2$)
